@echo off

REM Path to Visual Studio 2022 Developer Command Prompt
set "VS2022_DEV_CMD=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"

REM Check if the developer command prompt exists
if exist "%VS2022_DEV_CMD%" (
    echo Launching Visual Studio 2022 Developer Command Prompt...
    call "%VS2022_DEV_CMD%"
) else (
    echo Error: Visual Studio 2022 Developer Command Prompt not found!
    pause
    exit /b 1
)

REM Save current directory as project path
set "PROJECT_PATH=%cd%"

cd /d "%PROJECT_PATH%"

REM -------------------------------
REM Create .vscode folder if missing
REM -------------------------------
if not exist ".vscode" (
    echo Creating .vscode folder...
    mkdir ".vscode"
) else (
    echo .vscode folder already exists.
)

REM -------------------------------
REM Create tasks.json file with default content
REM -------------------------------
set "TASKS_FILE=.vscode\tasks.json"

if not exist "%TASKS_FILE%" (
    echo Creating tasks.json with simple content...

    (
        echo {
            echo "tasks": [
            echo // Folder Structure
            echo {
                echo "type": "shell",
                echo "label": "Generate Common Standard Folder Structure",
                echo "command": "cmd",
                echo "args": [
                    echo "/C",
                    echo "mkdir src",
                    echo "src\\core",
                    echo "src\\systems",
                    echo "src\\utils",
                    echo "include",
                    echo "include\\${workspaceFolderBasename}",
                    echo "include\\${workspaceFolderBasename}\\core",
                    echo "include\\${workspaceFolderBasename}\\systems",
                    echo "include\\${workspaceFolderBasename}\\utils",
                    echo "libs",
                    echo "external",
                    echo "assets",
                    echo "build",
                    echo "build\\Release",
                    echo "build\\Debug",
                    echo "build\\GPP",
                    echo "tests",
                    echo "docs",
                echo ],
                echo "options": {
                    echo "cwd": "${workspaceFolder}"
                echo },
                echo "group": "build",
                echo "detail": "Task generated by Alijimpa."
            echo },
        echo ],
        echo "version": "2.0.0"
        echo }
    ) > "%TASKS_FILE%"

) else (
    echo tasks.json already exists, skipping creation.
)

REM Open project in VSCode
code .

exit